### PR TITLE
Fix for webpack

### PR DESCRIPTION
**Pull request by MaxSvargal**
In webpack bundle this module present as:
`/***/ function(module, exports) {
    [
      "🀄",
      "🃏",
      "🅰",
         ...
  ]
}`

But need
`/***/ function(module, exports) {
  module.exports = [
      "🀄",
      "🃏",
      "🅰",
         ...
  ]
}`

This patch fix it.

### CODE REVIEW

**Comment by Kikobeats** [comment]
Good, but list is autogenerated using update.js 
https://github.com/Kikobeats/emojis-list/blob/master/update.js

consider update this script to generate the new file

**Comment by Kikobeats** [comment]
@MaxSvargal Just as idea, but what happens if you require the json as:

```
var emojis = require('emojis-list/emojis.json')
```

and you create the file that you need?

**Comment by MaxSvargal** [comment]
Your module is dependence of webpack's loader-utils ( https://github.com/webpack/loader-utils )
So i need to make a pull request into that repository...

**Comment by MaxSvargal** [comment]
`var emojis = require('emojis-list/emojis.json')`
I check you suggestion, but it does not work. Output:
`function(module, exports) { [] }`

**Comment by Kikobeats** [comment]
Ok, then we can change the interface, but please use `update.js` for generate the file instead of hard-edit the file 😄

**Comment by MaxSvargal** [comment]
@Kikobeats I think you do it better than me)

**Comment by Kikobeats** [comment]
I have a vague memory of something similar that I did in the past but I actually don't remember now

I think that I used [fs.writeFile](https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback)

**Comment by Kikobeats** [comment]
@MaxSvargal  check new documentation for be possible load using webpack 👍

**Comment by bestmike007** [comment]
@MaxSvargal I'm not sure why webpack loader-utils package include this emojis-list package in version 0.2.14 w/o resolving the issue that webpack needs the json-loader to load the emojis-list.json file. The solution w/o any monkey patch to webpack related packages is to include the following config in the webpack config file:

``` js
// ...
  module: {
    loaders: [{
      test: /\.jsx?$/,
      exclude: /(node_modules|bower_components|vendor)/,
      loader: 'babel',
      query: {
        retainLines: true,
        cacheDirectory: true,
        presets: ['react', 'es2015', 'stage-2']
      }
    }, {
      test: /\.json$/,
      loader: "json"
    }]
  }
// ...
```

But if you have other json files to require, make it similar to this (not tested yet):

``` js
  module: {
    loaders: [{
      test: /\.jsx?$/,
      exclude: /(node_modules|bower_components|vendor)/,
      loader: 'babel',
      query: {
        retainLines: true,
        cacheDirectory: true,
        presets: ['react', 'es2015', 'stage-2']
      }
    }, {
      test: /emojis\.json$/,
      loader: "json"
    }, {
      test: /\.jpe?g$|\.gif$|\.png$|\.svg|\.json$/i,
      exclude: /emojis\.json$/,
      loader: "file-loader?name=[path][name].[ext]?[hash]"
    }]
  }
```

I'm still trying to figure out whether this is a common issue or not. Hope it helps. Is there a link to the document you mentioned? @Kikobeats

**Comment by Kikobeats** [comment]
@bestmike007 the readme of the repository

**Pull request closed without merging**
