### PR TITLE
V2: Update Edition

### PR DESCRIPTION
**Pull request by Kikobeats**
Hello,

I created a new branch that will be shipped as `2.0.0` tag.

This version is based in the @bestmike007 PR but I do the minimal and elegant changes to make code more easy to read (and maintainable).

Also this version want to fix the problems related with webpack transformers, so I need the feeback of you guys (@p2227, @MaxSvargal)

### CODE REVIEW

**Comment by Kikobeats** [comment]
Could be nice add a test to be sure that webpack load correctly this new version

**Comment by bestmike007** [comment]
@Kikobeats It's still necessary to fix v1.0.x for webpack loader-utils because they're still using v1.0.x.

**Comment by Kikobeats** [comment]
@bestmike007 true. I'm going to fix it and release it as minor change and deprecate 1.x version in favour of 2.x as well.

**Comment by bestmike007** [comment]
Great, nice refactoring btw.

**Comment by Kikobeats** [comment]
@bestmike007 can you confirm that this index works fine with webpack?

**Comment by bestmike007** [comment]
I read their code, so theoretically it is.

**Comment by p2227** [comment]
that's great!

**Pull request merged**
