### PR TITLE
Add new emoji

### PR DESCRIPTION
**Pull request by Kikobeats**
I run the script for update the emoji file, but looks like not possible resolve all emoji variations.

I don't know how this breaks the next version, so I want to determinate if is necessary a workaround or just they looks weird but is correct.

### CODE REVIEW

**Comment by Kikobeats** [comment]
Anybody can help me with this? @bestmike007 @p2227 @astoilkov

**Comment by Kikobeats** [comment]
Apparently all is correct:

http://emojipedia.org/woman-with-bunny-ears-type-6/

I think that basically doesn't exist a representation for that, but sounds strange for me.

**Comment by bestmike007** [comment]
You hadn't installed the `he` package.

**Comment by Kikobeats** [comment]
@bestmike007 actually not necessary; I updated the PR.

**Comment by bestmike007** [comment]
But you're still using it. https://github.com/Kikobeats/emojis-list/blob/master/update.js#L5

And the script works fine on my computer.

``` bash
$ npm run update

> emojis-list@2.0.1 update C:\Projects\emojis-list
> node update

debug detected 🀄
debug detected 🃏
debug detected 🅰
...
debug detected ㊙
debug detected 3⃣
debug detected 4⃣
debug detected 5⃣
debug detected 6⃣
debug detected 7⃣
debug detected 8⃣
debug detected 9⃣
debug detected ©
debug detected ®
debug detected 
 info total: 2477
 info saved at index.js

$ git diff index.js
warning: LF will be replaced by CRLF in index.js.
The file will have its original line endings in your working directory.
```

**Comment by Kikobeats** [comment]
@bestmike007 you're right, thanks for that, need to be removed, it's unnecessary 😄 .

**Comment by bestmike007** [comment]
What about this: https://github.com/Kikobeats/emojis-list/blob/master/update.js#L29

**Pull request merged**
